# Generated by Django 5.1.7 on 2025-04-12 18:47

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Habilidad',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, unique=True, verbose_name='Nombre de la Habilidad')),
                ('description', models.TextField(verbose_name='Descripción de la Habilidad')),
            ],
            options={
                'verbose_name': 'Habilidad',
                'verbose_name_plural': 'Habilidades',
            },
        ),
        migrations.CreateModel(
            name='Tipo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, unique=True, verbose_name='Nombre del Tipo')),
            ],
            options={
                'verbose_name': 'Tipo',
                'verbose_name_plural': 'Tipos',
            },
        ),
        migrations.CreateModel(
            name='Pokemon',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('pokedex_number', models.PositiveIntegerField(unique=True, verbose_name='Número de la Pokédex')),
                ('name', models.CharField(max_length=100, verbose_name='Nombre del Pokémon')),
                ('pokedex_entry', models.TextField(verbose_name='Entrada de la Pokédex')),
                ('hp', models.PositiveIntegerField(verbose_name='Vida')),
                ('attack', models.PositiveIntegerField(verbose_name='Ataque')),
                ('defense', models.PositiveIntegerField(verbose_name='Defensa')),
                ('special_attack', models.PositiveIntegerField(verbose_name='Ataque Especial')),
                ('special_defense', models.PositiveIntegerField(verbose_name='Defensa Especial')),
                ('speed', models.PositiveIntegerField(verbose_name='Velocidad')),
                ('normal_image', models.ImageField(blank=True, null=True, upload_to='static/pokemons/normal/', verbose_name='Imagen Normal')),
                ('shiny_image', models.ImageField(blank=True, null=True, upload_to='pokemons/pokemons/shiny/', verbose_name='Imagen Shiny')),
                ('weight', models.DecimalField(decimal_places=2, max_digits=5, verbose_name='Peso')),
                ('height', models.DecimalField(decimal_places=2, max_digits=5, verbose_name='Altura')),
                ('capture_rate', models.PositiveIntegerField(verbose_name='Ratio de Captura')),
                ('gender', models.CharField(choices=[('male', 'Macho'), ('female', 'Hembra'), ('both', 'Ambos'), ('unknown', 'Desconocido')], max_length=20, verbose_name='Posibles géneros')),
                ('primary_type', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='pokemones_tipo_principal', to='pokemon.tipo', verbose_name='Tipo Principal')),
                ('secondary_type', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='pokemones_tipo_secundario', to='pokemon.tipo', verbose_name='Tipo Secundario')),
            ],
            options={
                'verbose_name': 'Pokémon',
                'verbose_name_plural': 'Pokemons',
            },
        ),
        migrations.CreateModel(
            name='Movimiento',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='Nombre del Movimiento')),
                ('movement_type', models.CharField(choices=[('status', 'Estado'), ('physical', 'Físico'), ('special', 'Especial')], max_length=10, verbose_name='Tipo de Movimiento')),
                ('power', models.PositiveIntegerField(verbose_name='Poder')),
                ('description', models.TextField(blank=True, verbose_name='Descripción del Efecto Secundario')),
                ('type', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='pokemon.tipo', verbose_name='Tipo del Movimiento')),
            ],
            options={
                'verbose_name': 'Movimiento',
                'verbose_name_plural': 'Movimientos',
            },
        ),
        migrations.CreateModel(
            name='EfectividadTipo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('multiplier', models.FloatField(help_text='Por ejemplo: 2.0, 0.5, 0.0, 1.0', verbose_name='Multiplicador')),
                ('attacking_type', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='ventajas_ofensivas', to='pokemon.tipo', verbose_name='Tipo Atacante')),
                ('defending_type', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='ventajas_defensivas', to='pokemon.tipo', verbose_name='Tipo Defensor')),
            ],
            options={
                'verbose_name': 'Efectividad de Tipo',
                'verbose_name_plural': 'Efectividades de Tipos',
                'unique_together': {('attacking_type', 'defending_type')},
            },
        ),
    ]
