# Generated by Django 5.1.7 on 2025-04-14 21:15

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pokemon', '0002_rename_habilidad_ability_rename_movimiento_move_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='EggGroup',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, unique=True, verbose_name='Nombre del Grupo Huevo')),
            ],
            options={
                'verbose_name': 'Grupo Huevo',
                'verbose_name_plural': 'Grupos Huevo',
            },
        ),
        migrations.CreateModel(
            name='MegaEvolution',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='Nombre de Mega Evolución')),
                ('normal_image', models.ImageField(upload_to='img/pokemons/megaevolutions/normal/', verbose_name='Imagen Mega Evolución Normal')),
                ('shiny_image', models.ImageField(upload_to='img/pokemons/megaevolutions/shiny/', verbose_name='Imagen Mega Evolución Shiny')),
                ('hp', models.PositiveIntegerField(verbose_name='Vida')),
                ('attack', models.PositiveIntegerField(verbose_name='Ataque')),
                ('defense', models.PositiveIntegerField(verbose_name='Defensa')),
                ('special_attack', models.PositiveIntegerField(verbose_name='Ataque Especial')),
                ('special_defense', models.PositiveIntegerField(verbose_name='Defensa Especial')),
                ('speed', models.PositiveIntegerField(verbose_name='Velocidad')),
                ('evolution_method', models.TextField(blank=True, null=True, verbose_name='Método de Mega Evolución')),
            ],
            options={
                'verbose_name': 'Mega Evolución',
                'verbose_name_plural': 'Mega Evoluciones',
            },
        ),
        migrations.AlterUniqueTogether(
            name='typeeffectiveness',
            unique_together=set(),
        ),
        migrations.AddField(
            model_name='pokemon',
            name='evolution_method',
            field=models.TextField(blank=True, null=True, verbose_name='Método de Evolución'),
        ),
        migrations.AddField(
            model_name='pokemon',
            name='generation',
            field=models.PositiveSmallIntegerField(default=1, verbose_name='Generación'),
        ),
        migrations.AddField(
            model_name='pokemon',
            name='hidden_ability',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='hidden_pokemons', to='pokemon.ability', verbose_name='Habilidad Oculta'),
        ),
        migrations.AddField(
            model_name='pokemon',
            name='moves',
            field=models.ManyToManyField(to='pokemon.move', verbose_name='Movimientos'),
        ),
        migrations.AddField(
            model_name='pokemon',
            name='pre_evolution',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='evolutions', to='pokemon.pokemon', verbose_name='Evoluciona de'),
        ),
        migrations.AddField(
            model_name='pokemon',
            name='primary_ability',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='primary_pokemons', to='pokemon.ability', verbose_name='Habilidad Principal'),
        ),
        migrations.AddField(
            model_name='pokemon',
            name='secondary_ability',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='secondary_pokemons', to='pokemon.ability', verbose_name='Habilidad Secundaria'),
        ),
        migrations.AddField(
            model_name='type',
            name='icon',
            field=models.ImageField(default='img/types/default_icon.png', upload_to='img/types', verbose_name='Icono del Tipo'),
        ),
        migrations.AddField(
            model_name='type',
            name='rgb',
            field=models.CharField(default='#FFFFFF', help_text='Ejemplo: #FF0000', max_length=7, verbose_name='Color HEX'),
        ),
        migrations.AlterField(
            model_name='pokemon',
            name='normal_image',
            field=models.ImageField(blank=True, null=True, upload_to='img/pokemons/normal/', verbose_name='Imagen Normal'),
        ),
        migrations.AlterField(
            model_name='pokemon',
            name='primary_type',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='pokemons_tipo_principal', to='pokemon.type', verbose_name='Tipo Principal'),
        ),
        migrations.AlterField(
            model_name='pokemon',
            name='secondary_type',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='pokemons_tipo_secundario', to='pokemon.type', verbose_name='Tipo Secundario'),
        ),
        migrations.AlterField(
            model_name='pokemon',
            name='shiny_image',
            field=models.ImageField(blank=True, null=True, upload_to='img/pokemons/shiny/', verbose_name='Imagen Shiny'),
        ),
        migrations.AddConstraint(
            model_name='typeeffectiveness',
            constraint=models.UniqueConstraint(fields=('attacking_type', 'defending_type'), name='unique_type_effectiveness'),
        ),
        migrations.AddField(
            model_name='pokemon',
            name='egg_groups',
            field=models.ManyToManyField(to='pokemon.egggroup', verbose_name='Grupos Huevo'),
        ),
        migrations.AddField(
            model_name='megaevolution',
            name='ability',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='pokemon.ability', verbose_name='Habilidad'),
        ),
        migrations.AddField(
            model_name='megaevolution',
            name='base_pokemon',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='megaevolutions', to='pokemon.pokemon', verbose_name='Pokémon Base'),
        ),
    ]
