# Generated by Django 5.1.7 on 2025-04-15 13:54

from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pokemon', '0003_egggroup_megaevolution_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='typeeffectiveness',
            name='multiplier',
            field=models.DecimalField(choices=[(Decimal('0.0'), '0x'), (Decimal('0.5'), '0.5x'), (Decimal('1.0'), '1x'), (Decimal('2.0'), '2x')], decimal_places=2, max_digits=3, verbose_name='Multiplicador'),
        ),
    ]
