# Generated by Django 5.1.7 on 2025-04-16 15:29

from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pokemon', '0004_alter_typeeffectiveness_multiplier'),
    ]

    operations = [
        migrations.AddField(
            model_name='move',
            name='accuracy',
            field=models.PositiveIntegerField(default=100, verbose_name='Precisión'),
        ),
        migrations.AlterField(
            model_name='move',
            name='power',
            field=models.PositiveIntegerField(default=0, verbose_name='Poder'),
        ),
        migrations.AlterField(
            model_name='typeeffectiveness',
            name='multiplier',
            field=models.DecimalField(choices=[(Decimal('0.0'), '0x'), (Decimal('0.5'), '0.5x'), (Decimal('1.0'), '1x'), (Decimal('2.0'), '2x')], decimal_places=2, default=Decimal('1.0'), max_digits=3, verbose_name='Multiplicador'),
        ),
    ]
