# Generated by Django 5.1.7 on 2025-04-20 21:13

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pokemon', '0005_move_accuracy_alter_move_power_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='megaevolution',
            name='height',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=5, verbose_name='Altura'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='megaevolution',
            name='primary_type',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='megas_tipo_principal', to='pokemon.type', verbose_name='Tipo Principal'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='megaevolution',
            name='secondary_type',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='megas_tipo_secundario', to='pokemon.type', verbose_name='Tipo Secundario'),
        ),
        migrations.AddField(
            model_name='megaevolution',
            name='weight',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=5, verbose_name='Peso'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='move',
            name='description',
            field=models.TextField(blank=True, verbose_name='Descripción del Movimiento'),
        ),
    ]
