# Generated by Django 5.1.7 on 2025-05-04 10:11

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pokemon', '0006_megaevolution_height_megaevolution_primary_type_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='megaevolution',
            name='creator',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL, verbose_name='Creador'),
        ),
        migrations.AddField(
            model_name='pokemon',
            name='creator',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL, verbose_name='Creador'),
        ),
        migrations.AlterField(
            model_name='pokemon',
            name='pokedex_number',
            field=models.PositiveIntegerField(blank=True, null=True, unique=True, verbose_name='Número de la Pokédex'),
        ),
    ]
