# Generated by Django 5.1.7 on 2025-05-04 10:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('pokemon', '0007_megaevolution_creator_pokemon_creator_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='megaevolution',
            name='shiny_image',
        ),
        migrations.RemoveField(
            model_name='pokemon',
            name='shiny_image',
        ),
    ]
