# Generated by Django 5.1.7 on 2025-05-04 10:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pokemon', '0008_remove_megaevolution_shiny_image_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='megaevolution',
            name='normal_image',
            field=models.ImageField(upload_to='img/pokemons/megaevolutions/', verbose_name='Imagen Mega Evolución Normal'),
        ),
        migrations.AlterField(
            model_name='pokemon',
            name='normal_image',
            field=models.ImageField(blank=True, null=True, upload_to='img/pokemons/', verbose_name='Imagen Normal'),
        ),
    ]
